In [4]:
import numpy as np
import pandas as pd

## Pivot Tables (Use For Aggregrations)

In [11]:
data = {
    'Date' : pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 
                'East', 'West', 'North', 'South', 
                'East', 'West', 'North', 'South', 
                'East', 'West', 'North', 'South', 
                'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice',
            'John', 'Mary', 'Bob', 'Alice',
            'John', 'Mary', 'Bob', 'Alice',
            'John', 'Mary', 'Bob', 'Alice',
            'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [12]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    586     88   John  January      Q1
1  2023-01-02       B   West    127     39   Mary  January      Q1
2  2023-01-03       C  North    295     58    Bob  January      Q1
3  2023-01-04       D  South    259     41  Alice  January      Q1
4  2023-01-05       A   East    186     45   John  January      Q1
5  2023-01-06       B   West    805     67   Mary  January      Q1
6  2023-01-07       C  North    370     25    Bob  January      Q1
7  2023-01-08       D  South    329     81  Alice  January      Q1
8  2023-01-09       A   East    763     15   John  January      Q1
9  2023-01-10       B   West    752     73   Mary  January      Q1
10 2023-01-11       C  North    111     11    Bob  January      Q1
11 2023-01-12       D  South    559     21  Alice  January      Q1
12 2023-01-13       A   East    122     74   John  January      Q1
13 2023-01-14       B   West    522     95   Mary  January      Q1
14 2023-01-15       C  North    713     37    Bob  January      Q1
15 2023-01-16       D  South    351     78  Alice  January      Q1
16 2023-01-17       A   East    774     68   John  January      Q1
17 2023-01-18       B   West    499     74   Mary  January      Q1
18 2023-01-19       C  North    880     83    Bob  January      Q1
19 2023-01-20       D  South    854     43  Alice  January      Q1

In [13]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product')

Product      A      B      C      D
Region
East     486.2    NaN    NaN    NaN
North      NaN    NaN  473.8    NaN
South      NaN    NaN    NaN  470.4
West       NaN  541.0    NaN    NaN

In [14]:
pd.pivot_table(df, values='Sales', index='Region', columns='Product', aggfunc='median')

Product      A      B      C      D
Region
East     586.0    NaN    NaN    NaN
North      NaN    NaN  370.0    NaN
South      NaN    NaN    NaN  351.0
West       NaN  522.0    NaN    NaN

In [15]:
pd.pivot_table(df, values=['Sales', 'Units'], index='Region', columns='Product') # values must be numeric

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     586.0    NaN    NaN    NaN  68.0   NaN   NaN   NaN
North      NaN    NaN  370.0    NaN   NaN   NaN  37.0   NaN
South      NaN    NaN    NaN  351.0   NaN   NaN   NaN  43.0
West       NaN  522.0    NaN    NaN   NaN  73.0   NaN   NaN

## Cross Tabs (Use For Counts)

In [16]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0