In [1]:
import numpy as np 
import pandas as pd

In [17]:
# loading the CSV data
df = pd.read_csv(r'anime.csv')

In [18]:
df

    Unnamed: 0  Rank                                          Title  Score
0            1     1             User-centric asynchronous capacity  86.69
1            2     2               Implemented bifurcated framework  88.43
2            3     3                  Virtual transitional database  98.48
3            4     4  Down-sized contextually-based instruction set  68.95
4            5     5                  Object-based exuding attitude  70.89
..         ...   ...                                            ...    ...
95          96    96                 Digitized even-keeled solution  75.71
96          97    97             Customizable asynchronous strategy  61.77
97          98    98                      Cloned didactic groupware  65.52
98          99    99               Open-architected optimal project  82.06
99         100   100               Adaptive intermediate moratorium  94.39

[100 rows x 4 columns]

In [19]:
df.head() # show top 5 rows

   Unnamed: 0  Rank                                          Title  Score
0           1     1             User-centric asynchronous capacity  86.69
1           2     2               Implemented bifurcated framework  88.43
2           3     3                  Virtual transitional database  98.48
3           4     4  Down-sized contextually-based instruction set  68.95
4           5     5                  Object-based exuding attitude  70.89

In [20]:
# make a new column for episode count
df.loc[2]['Title']

'Virtual transitional database'

In [16]:
def extract_episodes(txt):
    check = False
    data = ''
    for i in txt:
        if i == ')':
            check = False
            return data
        if i == '(':
            check = True
        if check == True:
            data = data + i

In [ ]:
df['Episodes'] = df['Title'].apply(extract_episodes)

In [ ]:
df['Episodes'] = df['Episodes'].str.replace(' eps', '')

In [ ]:
df['Episodes'] = df['Episodes'].astype(int)

In [6]:
# make a new column for time stamp
df.loc[2]['Title']

In [ ]:
def extract_time(txt):
    check = False
    data = ''
    for i in range(len(txt)):
        if txt[i] == ')':
            for j in range(i+1, i+20):
                data = data + j
            return data

In [ ]:
df['Total Time'] = df['Title'].apply(extract_time)

In [ ]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

def calculate_total_months(period): 
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1 # +1 to include the starting month
    except:
        return None
df['Months'] = df['Total Time'].apply(calculate_total_months)

In [ ]:
df

In [7]:
# which anime has the highest score 
df[df['Score'] == df['Score'].max()]['Title']

In [8]:
# give me top 5 highest scoring anime 
df['Title'].head()

In [9]:
# which anime has the highest episode count 
df['Episodes'] = df['Episodes'].max()

In [10]:
# animes with top 5 episode count

In [11]:
# which is longest running anime 
df['Months'] = df['Months'].max()